default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: 5

development:
  <<: *default
  database: backend_challenge_development

test:
  <<: *default
  database: backend_challenge_test

production:
  <<: *default
  database: backend_challenge_production
  username: backend_challenge
  password: <%= ENV['BACKEND_CHALLENGE_DATABASE_PASSWORD'] %>