# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d702ab9c6262169d20fd16f24bc8d6360bcf0ee972c1272f10b228a2533fa07496f1ae291f070b99c38e0289c0569523ffeb9e3ee120542ca51229a40681467

test:
  secret_key_base: 967bc81096fef6373ec3731c70f8054e7905c3e2977f3ca5210c78501ff9c5cdb8e4bba52211a26ab05c6bd276d4f105bc3445b87c50c8b7d0d54ee7e3574154

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
